export enum Paths {
  'auth_stack' = 'auth_stack',
  'login' = 'login',
  'forgot_password' = 'forgot_password',
  'app_stack' = 'app_stack',
  'discovery' = 'discovery',
  'island' = 'island',
  'inbox' = 'inbox',
  'inbox_stack' = 'inbox_stack',
  'new' = 'new',
  'menu' = 'menu',
  'profile' = 'profile',
  'profile_stack' = 'profile_stack',
  'chat' = 'chat',
  'update_text_field' = 'update_text_field',
}
